### ISSUE TITLE
npm start errors out

### ISSUE THREAD

**Issue by fopsdev** [Roustalski/au-demos#1]
btw. gulp watch works, nice demo :+1: 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\dev\\nodejs\\node.exe',
1 verbose cli   'C:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart aurelia-modular-demo@0.0.1
6 info start aurelia-modular-demo@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info aurelia-modular-demo@0.0.1 Failed to exec start script
9 verbose stack Error: aurelia-modular-demo@0.0.1 start: `DEBUG=au-demos-modular:* node src/server-node/bin/www`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\dev\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\dev\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid aurelia-modular-demo@0.0.1
11 verbose cwd c:\dev\temp\au-demos\modular
12 error Windows_NT 10.0.10586
13 error argv "C:\\dev\\nodejs\\node.exe" "C:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.2.4
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error aurelia-modular-demo@0.0.1 start: `DEBUG=au-demos-modular:* node src/server-node/bin/www`
17 error Exit status 1
18 error Failed at the aurelia-modular-demo@0.0.1 start script 'DEBUG=au-demos-modular:* node src/server-node/bin/www'.
18 error This is most likely a problem with the aurelia-modular-demo package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     DEBUG=au-demos-modular:* node src/server-node/bin/www
18 error You can get their info via:
18 error     npm owner ls aurelia-modular-demo
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by Roustalski** [comment]
Howdy. What version of npm and node are you running with?

**Comment by Roustalski** [comment]
@fopsdev Good afternoon. I just realized that the script is using a unix path:

```shell
DEBUG=au-demos-modular:* node src/server-node/bin/www
```
Try invoking node on the command line and put in the local windows path to ...\bin\www

Probably as easy as turning the forward slashes to back slashes

**Comment by Roustalski** [comment]
Let me know if you are still having issues.
